schema_version = "1.0.0"
id = "mio3copyweight"
name = "Mio3 Copy Weight"
version = "0.9.0"
tagline = "This is another extension"
maintainer = "Mio"
type = "add-on"
tags = ["Modeling"]
blender_version_min = "3.6.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/mio3io"
copyright = ["2024 Mio"]

